name: enc
on: 
  push:
    branches: master
    paths: 
      - '*.txt'

jobs:
  test:
    name: ENC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: enc
        run: |
          echo "hi" > auth
          openssl enc -aes-256-cbc -salt -in auth -out auth.enc -k ${{ secrets.GITHUB_TOKEN }}
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add auth.enc
          git commit -m "add auth file"
          git push ${REMOTE} master
          
