name: enc
on: 
  push:
    branches: a/b
    paths: 
      - '*.txt'

jobs:
  test:
    name: ENC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"    
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-          
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: enc
        run: |

          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          R=https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          
          git pull ${REMOTE}
          
          node .github/workflows/encrypt.js ${{ secrets.GITHUB_TOKEN }}
          
          git checkout master

          git status
          git add auth.enc
          git commit -m "add auth file"
          git push ${R} master
          
          node .github/workflows/enc.js ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
          
          node .github/workflows/decrypt.js ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}
          
