name: PR
on: [push]

jobs:
  test:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pr
        run: |
          echo "token ${{ secrets.GITHUB_TOKEN }}"
          
